#!/usr/bin/env bash
newcpp() {
	if [[ $# -ne 1 ]]; then
		echo "Usage: newcpp NAME"
		return 1
	fi
	if [[ "$1" == "run" || "$1" == "tests" || "$1" == "check" || "$1" == "bin" || "$1" == "" ]]; then
		echo "NAME cannot be 'bin', 'check', 'run', 'tests', or ''."
		return 1
	fi
	if [[ "$1" = *[[:space:]]* ]]; then
		echo "NAME cannot contain whitespace."
		return 1
	fi
	mkdir "$1"
	cd "$1"
	~/bin/_newcpp.sh $1
	return 0
}

